In [1]:
import numpy as np

**Task 1: Creating Arrays**

In [2]:
#Create a 1D NumPy array containing values from 1 to 10.
array1=np.array([1,2,3,4,5,6,7,8,9,10])


In [3]:
#Create a 2D array of size 3×3.
array2=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [4]:
#Create an array of zeros of size 4×4.
array3=np.array([[0,0,0,0],
                [0,0,0,0],
                [0,0,0,0],
                [0,0,0,0]])

In [9]:
#Create an array of ones of size 2×5
array4=np.ones((2,5))

In [12]:
#Display all arrays.
print("Task 1: Create arrays of various dimensions and display them:")
print("Array with elements: 1-10\n",array1,"\n")
print("3x3 array\n",array2,"\n")
print("4x4 of zeros\n",array3,'\n')
print("2x5 of ones\n",array4,"\n")

Task 1: Create arrays of various dimensions and display them:
Array with elements: 1-10
 [ 1  2  3  4  5  6  7  8  9 10] 

3x3 array
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

4x4 of zeros
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

2x5 of ones
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



**Task 2: Array Properties**

In [17]:
print("2.1 Find shape of array")
#I will use array4 for this
print(f"shape: {array4.shape}")


2.1 Find shape of array
shape: (2, 5)


In [18]:
print("2.2 Find total number of elements")
print(f"size: {array4.size}")

2.2 Find total number of elements
size: 10


In [21]:
print("2.3 Find data type of elements")
print(f"Data Type of elements: {array4.dtype}")


2.3 Find data type of elements
Data Type of elements: float64


In [20]:
print("2.4 Find number of dimensions")
print(f"Dimension: {array4.ndim}")


2.4 Find number of dimensions
Dimension: 2


In [22]:
#Explain why shape is important in AI
print("""
Importance in AI: Shape ensures data compatibility between layers (e.g., input features must match weight matrix dimensions).
""")


Importance in AI: Shape ensures data compatibility between layers (e.g., input features must match weight matrix dimensions).



**Task 3 — Indexing**

In [25]:
print("3.1 Create an array")
task3=np.array([10,20,30,40,50,60])

print("3.2 Access first element, last element and third element")
print(f"First: {task3[0]}, Last: {task3[-1]}, Third: {task3[2]}")

print("3.3 Print all values greater than 30")
print(f"Values > 30: {task3[task3 > 30]}")

3.1 Create an array
3.2 Access first element, last element and third element
First: 10, Last: 60, Third: 30
3.3 Print all values greater than 30
Values > 30: [40 50 60]


**Task 4 — Slicing**

In [28]:
#Using task 3 array for this
print("4.1 Extract elements from index 1 to 4.")
print(f"Index 1 to 4: {task3[1:5]}\n")

print("4.2 Reverse the array using slicing")
print(f"Reversed: {task3[::-1]}\n")

print(" 4.3 Extract alternate elements.")
print(f"Alternate: {task3[::2]}\n")

print("4.4 Create a 3×3 matrix and: Print first row, Print second column, Print last two rows")
matrix_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"First Row: {matrix_3x3[0, :]}")
print(f"Second Column: {matrix_3x3[:, 1]}")
print(f"Last Two Rows:\n{matrix_3x3[-2:, :]}")


4.1 Extract elements from index 1 to 4.
Index 1 to 4: [20 30 40 50]

4.2 Reverse the array using slicing
Reversed: [60 50 40 30 20 10]

 4.3 Extract alternate elements.
Alternate: [10 30 50]

4.4 Create a 3×3 matrix and: Print first row, Print second column, Print last two rows
First Row: [1 2 3]
Second Column: [2 5 8]
Last Two Rows:
[[4 5 6]
 [7 8 9]]


**Task 5: Vectorization**

In [29]:
print("5.1 Create an array")
vec_arr = np.array([1, 2, 3, 4, 5])
print("\n 5.2 Multiply all elements by 5 without using loops")
print(f"x5: {vec_arr * 5}")
print("\n 5.3 Add 10 to all elements")
print(f"+10: {vec_arr + 10}")
print("\n 5.4 Square all elements")
print(f"Square: {vec_arr ** 2}")
print("\n Importance in AI: It allows for parallel processing of data, significantly speeding up training compared to Python loops.")

5.1 Create an array

 5.2 Multiply all elements by 5 without using loops
x5: [ 5 10 15 20 25]

 5.3 Add 10 to all elements
+10: [11 12 13 14 15]

 5.4 Square all elements
Square: [ 1  4  9 16 25]

 Importance in AI: It allows for parallel processing of data, significantly speeding up training compared to Python loops.


**Task 6 — Broadcasting**


In [30]:
print("6.1 Create a 2D array 2x3")
b_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\n 6.2 Add value 10 to all elements using broadcasting.") 
print(f"Add 10: {b_arr + 10}")
print("\n 6.3 Multiply entire array by 2.")
print(f"Multiply 2: {b_arr * 2}")
# Importance: Broadcasting allows performing operations on arrays of different shapes without manually duplicating data.

6.1 Create a 2D array 2x3

 6.2 Add value 10 to all elements using broadcasting.
Add 10: [[11 12 13]
 [14 15 16]]

 6.3 Multiply entire array by 2.
Multiply 2: [[ 2  4  6]
 [ 8 10 12]]


**Task 7 — Matrix Addition and Subtraction**


In [31]:
print("7.1 Create two matrices of size 2×2")
m1, m2=np.array([[1,2],[3,4]]), np.array([[1,2],[3,4]])
print("7.2.1 Perform Addition and Subtraction")
print(f"Addition:\n{m1 + m2}\nSubtraction:\n{m1 - m2}")

7.1 Create two matrices of size 2×2
7.2.1 Perform Addition and Subtraction
Addition:
[[2 4]
 [6 8]]
Subtraction:
[[0 0]
 [0 0]]


**Task 8: Matrix Multiplication and Transpose**

In [32]:
print(f"Dot Product:\n {np.dot(m1,m2)}")
print(f"Transpose:\n {m1.T}")
print("""
NN Relation: Neural networks use matrix multiplication to calculate the weighted sum of inputs for every neuron layer ($Y = WX + B$).
"""
)

Dot Product:
 [[ 7 10]
 [15 22]]
Transpose:
 [[1 3]
 [2 4]]

NN Relation: Neural networks use matrix multiplication to calculate the weighted sum of inputs for every neuron layer ($Y = WX + B$).



**Task 9: Random Arrays**

In [33]:
print("9.1 Generate a random integer array of size 4×4 between 1 and 100.")
rand_int=np.random.randint(1,101,(4,4))
print("\n9.2 Generate random decimal values.")
rand_dec=np.random.random((2,2))
print("""\n 9.3. Find:
o Maximum value
o Minimum value
o Average value""")
print(f"Max: {rand_int.max()}, Min: {rand_int.min()}, Avg: {rand_int.mean()}")
print("9.4 Importance: Randomness is essential for initializing weights to break symmetry and for shuffling training data.")


9.1 Generate a random integer array of size 4×4 between 1 and 100.

9.2 Generate random decimal values.

 9.3. Find:
o Maximum value
o Minimum value
o Average value
Max: 99, Min: 7, Avg: 49.375
9.4 Importance: Randomness is essential for initializing weights to break symmetry and for shuffling training data.


**Task 10: Student Marks Analyzer**

In [34]:
marks = np.array([45, 82, 90, 30, 55, 88, 76, 40, 95, 60])
print(f"Avg: {marks.mean()}, High: {marks.max()}, Low: {marks.min()}")
print(f"Above 80: {np.sum(marks > 80)}")
print(f"Failed (<50): {marks[marks < 50]}")

Avg: 66.1, High: 95, Low: 30
Above 80: 4
Failed (<50): [45 30 40]


**Task 11: Image Pixel Simulation**

In [36]:
pixels = np.random.randint(0, 256, (5, 5))
print(f"Brightest: {pixels.max()}, Darkest: {pixels.min()}, Shape: {pixels.shape}")
print("Image Reading: AI views images as grids (arrays) of numbers representing light intensity (0-255).")

Brightest: 245, Darkest: 10, Shape: (5, 5)
Image Reading: AI views images as grids (arrays) of numbers representing light intensity (0-255).


**Task 12: Data Normalization**

In [37]:
print("12.1 Create an array of numerical data.")
data=np.array([0,50,100,150,200,250,300,350,400,450,500])
print("12.2. Normalize the dataset using formula:")
norm=(data-data.min()) / (data.max() -data.min())
print("12.3 Print normalized values.")
print(f"Normalized Data: {norm}")
print("12.4 Importance: Normalization ensures all features contribute equally and helps models converge faster during gradient descent.")

12.1 Create an array of numerical data.
12.2. Normalize the dataset using formula:
12.3 Print normalized values.
Normalized Data: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
12.4 Importance: Normalization ensures all features contribute equally and helps models converge faster during gradient descent.


**Task 13: Mini AI Dataset Project**

In [38]:
print("13.1 Create a small AI dataset containing: Age, Salary, Purchased Product")
dataset_list=[[23, 50083,0],[54,100000,1],[23,45792,1],[45,35465,0],[34,48318,1]]

13.1 Create a small AI dataset containing: Age, Salary, Purchased Product


In [39]:
print("13.2.1 Convert Dataset into NumPy array")
dataset=np.array(dataset_list)

13.2.1 Convert Dataset into NumPy array


In [40]:
print("13.2.2 Separate Input and Output Labels")
X = dataset[:, :2]  # Input features (Age, Salary)
y = dataset[:, 2]   # Output labels (Purchased)

13.2.2 Separate Input and Output Labels


In [41]:
print("13.2.3 Find average salary")
print(f"Avg Salary: {dataset[:, 1].mean()}")

13.2.3 Find average salary
Avg Salary: 55931.6


In [42]:
print("13.2.4 Find max age")
print(f"Max Age: {dataset[:, 0].max()}")

13.2.4 Find max age
Max Age: 54


In [43]:
print("13.2.5 Shape of Dataset")
print(f"Dataset Shape: {dataset.shape}")

13.2.5 Shape of Dataset
Dataset Shape: (5, 3)
